### ISSUE TITLE
Error when run .jar file

### ISSUE THREAD

**Issue by imardini98** [andreqi/coh-metrix-esp#3]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at Main.analyzeFile(Main.java:77)
	at Main.main(Main.java:53)
Caused by: java.lang.NullPointerException
	at pucp.edu.cohmetrixesp.utils.NativeUtils.saveLibrary(NativeUtils.java:91)
	at pucp.edu.cohmetrixesp.utils.NativeUtils.loadLibrary(NativeUtils.java:13)
	at pucp.edu.cohmetrixesp.utils.ImplFreelingAnalyzer.<init>(ImplFreelingAnalyzer.java:36)
	at pucp.edu.cohmetrixesp.utils.ImplFreelingAnalyzer.getInstance(ImplFreelingAnalyzer.java:30)
	at pucp.edu.cohmetrixesp.metrics.MetricsEngine.<init>(MetricsEngine.java:18)
	at pucp.edu.cohmetrixesp.metrics.MetricsEngine.<clinit>(MetricsEngine.java:17)
	... 2 more

**Comment by feralvam** [comment]
Hello,

Thanks for using Coh-Metrix-Esp. Could you provide more details so that we can reproduce the error? For instance:

1. What's the operating system you are using?
2. What's the specific command you used to run the application?
3. What's the complete error output?

**Comment by brunonavarro** [comment]
Hola Me sucede algo similar en MacOs BigSur 11.x 

Inicialmente al ejecutar el comando 

`java -jar coh-metrix-esp.jar -i /INPUT/input-30-07-2025.txt -o /OUTPUT/output-metrix-file-30-07-2025.json`

salia el error : 

`jar:file:/Users/brunonavarro/Downloads/COH-METRIX-ESP/coh-metrix-esp.jar!/libs/osx-x86_64/libfreeling_javaAPI.dylib
Saved libfile: /var/folders/9j/lk6hjb3s1s39rcp103_ctrjh0000gn/T/freeling_javaAPI-3667758715649982889.tmp
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/9j/lk6hjb3s1s39rcp103_ctrjh0000gn/T/freeling_javaAPI-3667758715649982889.tmp: dlopen(/private/var/folders/9j/lk6hjb3s1s39rcp103_ctrjh0000gn/T/freeling_javaAPI-3667758715649982889.tmp, 1): Library not loaded: /usr/local/opt/boost/lib/libboost_system-mt.dylib
  Referenced from: /private/var/folders/9j/lk6hjb3s1s39rcp103_ctrjh0000gn/T/freeling_javaAPI-3667758715649982889.tmp
  Reason: image not found
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at pucp.edu.cohmetrixesp.utils.NativeUtils.loadLibrary(NativeUtils.java:13)
	at pucp.edu.cohmetrixesp.utils.ImplFreelingAnalyzer.<init>(ImplFreelingAnalyzer.java:36)
	at pucp.edu.cohmetrixesp.utils.ImplFreelingAnalyzer.getInstance(ImplFreelingAnalyzer.java:30)
	at pucp.edu.cohmetrixesp.metrics.MetricsEngine.<init>(MetricsEngine.java:18)
	at pucp.edu.cohmetrixesp.metrics.MetricsEngine.<clinit>(MetricsEngine.java:17)
	at Main.analyzeFile(Main.java:77)
	at Main.main(Main.java:53)`

El cual luego de hacer un enlace simbolico salio el siguiente error: 

`jar:file:/Users/brunonavarro/Downloads/COH-METRIX-ESP/coh-metrix-esp.jar!/libs/osx-x86_64/libfreeling_javaAPI.dylib
Saved libfile: /var/folders/9j/lk6hjb3s1s39rcp103_ctrjh0000gn/T/freeling_javaAPI-13993205284961401604.tmp
dyld: lazy symbol binding failed: Symbol not found: __ZN8freeling4macoC1ERKNS_12maco_optionsE
  Referenced from: /private/var/folders/9j/lk6hjb3s1s39rcp103_ctrjh0000gn/T/freeling_javaAPI-13993205284961401604.tmp
  Expected in: /usr/local/opt/freeling/lib/libfreeling.dylib

dyld: Symbol not found: __ZN8freeling4macoC1ERKNS_12maco_optionsE
  Referenced from: /private/var/folders/9j/lk6hjb3s1s39rcp103_ctrjh0000gn/T/freeling_javaAPI-13993205284961401604.tmp
  Expected in: /usr/local/opt/freeling/lib/libfreeling.dylib

zsh: abort      java -jar coh-metrix-esp.jar -i /INPUT/input-30-07-2025.txt -o`

Serian tan amables de ayudarme a comprender la causa del error? Gracias.

**Comment by feralvam** [comment]
Estimado Bruno. Gracias por tu interés en la herramienta. Desafortunamente, CohMetrix-Esp ya no está siendo actulizada ni soportada. Te podría recomendar usar https://github.com/iapucp/pucp-metrix.
